// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Ri2MV7K6_5QJGgoNtfN4EniQNNK6Xl0',
    appId: '1:717774586412:web:68174a557ce0d6c03f4789',
    messagingSenderId: '717774586412',
    projectId: 'smartfarmtomato',
    authDomain: 'smartfarmtomato.firebaseapp.com',
    databaseURL: 'https://smartfarmtomato-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartfarmtomato.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFiVQvRfaJFZKA7h5YVRCIg8VrNSmcfoc',
    appId: '1:717774586412:android:73eba5f22db5e6843f4789',
    messagingSenderId: '717774586412',
    projectId: 'smartfarmtomato',
    databaseURL: 'https://smartfarmtomato-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartfarmtomato.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Ri2MV7K6_5QJGgoNtfN4EniQNNK6Xl0',
    appId: '1:717774586412:web:ae9f2a6bc740073d3f4789',
    messagingSenderId: '717774586412',
    projectId: 'smartfarmtomato',
    authDomain: 'smartfarmtomato.firebaseapp.com',
    databaseURL: 'https://smartfarmtomato-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartfarmtomato.firebasestorage.app',
  );

}